name: Update config

on:
  workflow-dispatch:
  # schedule

jobs:
  call-reusable:
    name: update config
    uses: IvanZosimov/reusable-workflows-fork/.github/workflows/update-tool-config-reusable.yml.yml@main
