name: Update tool configs 2
on: 
    workflow_dispatch:
    schedule:
      - cron:  '0 3 * * 0'
    
jobs:
  update-configs:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v3 # downloads current repo
      with:
        path: 'current'
        
    - uses: actions/checkout@v3 # downloads example repo
      with:
        repository: 'IvanZosimov/reusable-workflows-fork'
        path: 'example'

    - name: Configure git service account
      run: |       
        git config --global user.name 'Service account'
        git config --global user.email 'no-reply@microsoft.com'

    - name: Update configuration files
      run: |       
        BRANCH_NAME="update-tool-config"
        echo "BRANCH_NAME=update-tool-config" >> $GITHUB_ENV
        cd "./current"
        git checkout -b $BRANCH_NAME

        cp -f -r ${{github.workspace}}/example/* ${{github.workspace}}/current/
        
    - name: Create commit and push changes
      id: successful-commit
      run: |     
        
        cd "./current"
        git add .
        if git commit -m "Update tool configuration files"; then
            git push origin ${{env.BRANCH_NAME}} -f
            echo "STATUS=true" >> $GITHUB_OUTPUT
        else
        
            echo "::notice title=Workflow notice::No updates were found in the example repo."
            echo "STATUS=false" >> $GITHUB_OUTPUT
        fi     
    
    - name: Create pull request
      if: ${{ steps.successful-commit.outputs.STATUS == 'true' }}
      run: |
         curl \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{github.token}}"\
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{github.repository}}/pulls \
          -d '{"title":"'"ESLinter/Prettier configurations update from $(date +'%m/%d/%Y')"'","body":"In the scope of this PR ESLint or Prettier configuration files should be updated to match with example configuration files stored in '"[reusable-workflows](https://github.com/actions/reusable-workflows)"' repository.","head":"${{env.BRANCH_NAME}}","base":"main"}'
        
        
