name: Update tool configs
on: 
    workflow_dispatch:
    repository_dispatch:
      types: [test]
    
jobs:
  update-configs:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v3 # downloads current repo
      with:
        path: 'current'
        
    - uses: actions/checkout@v3 # downloads example repo
      with:
        repository: 'IvanZosimov/reusable-workflows-fork'
        path: 'example'

    - name: Update configuration files
      run: |       
        git config --global user.name automation
        git config --global user.email github-actions@github.com
        git config --global pull.ff only
        
        cd "${{github.workspace}}/current"
        git checkout -b update-tool-config-branch
        git pull origin update-tool-config-branch

        cp -f  "${{github.workspace}}/example/.eslintrc.json" "${{github.workspace}}/current/.eslintrc.json"
        cp -f  "${{github.workspace}}/example/.prettierrc.json" "${{github.workspace}}/current/.prettierrc.json"
        
        git add .
        git commit -m "Update tool configuration files"
        git push origin update-tool-config-branch
    
    - name: Create pull request
      run: |
        curl \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $PAT"\
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/IvanZosimov/TestRepo/pulls \
          -d '{"title":"ESLinter and Prettier configurations update","body":"Please pull these awesome changes in!","head":"update-tool-config","base":"main"}'
        
        
