# Some workflow
name: Update tool configs
on: 
    workflow_dispatch:
    # TO_DO: schedule
    
jobs:
  update-configs:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v3 # downloads current repo
      with:
        path: 'current'
    - uses: actions/checkout@v3 # downloads example repo
      with:
        repository: 'IvanZosimov/reusable-workflows-fork'
        path: 'example'
    - run: |
        if [ "$(git diff --ignore-space-at-eol "${{github.workspace}}/current/.eslintrc.json" "${{github.workspace}}/example/.eslintrc.json" | wc -l)" -gt "0" ]; then
            echo "ESLint config needs to be updated. These changes are found:"
            git diff "${{github.workspace}}/current/.eslintrc.json" "${{github.workspace}}/example/.eslintrc.json"
            exit 1
        fi

