# Some workflow
name: Update tool configs
on: 
    workflow_dispatch:
    # TO_DO: schedule
    
jobs:
  update-configs:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v3 # downloads current repo
      with:
        path: 'current'
    - uses: actions/checkout@v3 # downloads example repo
      with:
        repository: 'IvanZosimov/reusable-workflows-fork'
        path: 'example'
    - run: |
        if [ "$(git diff --ignore-space-at-eol "${{github.workspace}}/current/.eslintrc.json" "${{github.workspace}}/example/.eslintrc.json" | wc -l)" -gt "0" ]; then
            echo "ESLint config needs to be updated. These changes are found:"
            git diff "${{github.workspace}}/current/.eslintrc.json" "${{github.workspace}}/example/.eslintrc.json"
            exit 1
        fi
      id: diff
        
    - name: Update ESLint config file
      if: ${{failure() && steps.diff.conclusion == 'failure'}}
      run: |
        cd "${{github.workspace}}/current"
        git config user.name github-actions
        git config user.email github-actions@github.com
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git checkout -b update-tool-config
        git status
        cp -f  "${{github.workspace}}/example/.eslintrc.json" "${{github.workspace}}/current/.eslintrc.json"
        git status
        if [ "$(git diff --ignore-space-at-eol "${{github.workspace}}/current/.eslintrc.json" "${{github.workspace}}/example/.eslintrc.json" | wc -l)" -gt "0" ]; then
            echo "ESLint config needs to be updated. These changes are found:"
            git diff "${{github.workspace}}/current/.eslintrc.json" "${{github.workspace}}/example/.eslintrc.json"
            exit 1
        fi
        git add .
        git commit -m "Update tool config"
        git push origin update-tool-config
        
        
