# Some workflow
name: Update tool configs
on: 
    workflow_dispatch:
    # TO_DO: schedule
    
jobs:
  update-configs:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v3 # downloads current repo
      with:
        path: 'current'
    - uses: actions/checkout@v3 # downloads example repo
      with:
        repository: 'actions/reusable-workflows-fork'
        path: 'example'
    - run: |
        diff "${{github.workspace}}/current/.eslintrc.json" "${{github.workspace}}/example/.eslintrc.json"

