# Some workflow
name: Update tool configs
on: 
    workflow_dispatch:
    # TO_DO: schedule
    
jobs:
  update-configs:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v3 # downloads current repo
      with: 
        path: 'current'
    - uses: actions/checkout@v3 # downloads example repo
      with:
        repository: 'actions/reusable-workflows'
        path: 'example'
    - run: |
        ls '${{github.workspace}}/current'
        if [ "$(git diff --ignore-space-at-eol '${{github.workspace}}/../current/.eslintrc.json' '${{github.workspace}}/../example/.eslintrc.json' | wc -l)" -gt "0" ]; then
            echo "Detected eslint config changes. See them below:"
            git diff '${{github.workspace}}/../current/.eslintrc.json' '${{github.workspace}}/../example/.eslintrc.json'
            exit 1
        fi
